#!/usr/bin/env python3
"""Generate sitemap.xml from the working tree — on demand, no build step.

Mirrors scripts/gen_feed.py's model: run it by hand in the same commit as (or
the commit after) a content change; check_site.py INV-32 remains the drift
gate, and this script's --check mode fails when the file on disk differs from
what the tree would generate.

    python3 scripts/gen_sitemap.py            # rewrite sitemap.xml
    python3 scripts/gen_sitemap.py --check    # exit 1 if sitemap.xml is stale

lastmod is each file's last git commit date (a dirty or untracked file falls
back to today, like gen_feed's date fallback). Priorities follow the standing
convention: 1.0 root · 0.8 section indexes · 0.7 book detail pages · 0.6
posts. 404.html and the PDFs stay excluded (the detail page is what gets
promoted — see robots.txt).
"""
import glob
import os
import subprocess
import sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://anirach.com"
SECTIONS = ["blog", "books", "news", "projects", "publications"]


def git_date(rel):
    dirty = subprocess.run(["git", "status", "--porcelain", "--", rel],
                           cwd=ROOT, capture_output=True, text=True).stdout.strip()
    if dirty:
        return date.today().isoformat()
    out = subprocess.run(["git", "log", "-1", "--format=%ad", "--date=short", "--", rel],
                         cwd=ROOT, capture_output=True, text=True).stdout.strip()
    return out or date.today().isoformat()


def pages():
    """Yield (loc, rel_path, priority) in the file's stable order."""
    yield f"{SITE}/", "index.html", "1.0"
    for s in SECTIONS:
        yield f"{SITE}/{s}/", f"{s}/index.html", "0.8"
    for p in sorted(glob.glob(os.path.join(ROOT, "books", "*.html"))):
        rel = os.path.relpath(p, ROOT)
        if rel.endswith("index.html"):
            continue
        yield f"{SITE}/{rel}", rel, "0.7"
    for p in sorted(glob.glob(os.path.join(ROOT, "blog", "*.html"))):
        rel = os.path.relpath(p, ROOT)
        if rel.endswith("index.html"):
            continue
        yield f"{SITE}/{rel}", rel, "0.6"


def render():
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<!-- GENERATED by scripts/gen_sitemap.py from the working tree.',
             '     Regenerate after adding or substantively editing a page; check_site.py',
             '     INV-32 fails when a page is missing, and gen_sitemap.py --check fails',
             '     on any drift. lastmod = last git commit per file. -->',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, rel, prio in pages():
        lines += ["  <url>",
                  f"    <loc>{loc}</loc>",
                  f"    <lastmod>{git_date(rel)}</lastmod>",
                  f"    <priority>{prio}</priority>",
                  "  </url>"]
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def main():
    out = os.path.join(ROOT, "sitemap.xml")
    fresh = render()
    if "--check" in sys.argv:
        current = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if current != fresh:
            print("sitemap.xml is STALE — run: python3 scripts/gen_sitemap.py")
            sys.exit(1)
        print("sitemap.xml is fresh")
        return
    with open(out, "w", encoding="utf-8") as f:
        f.write(fresh)
    n = fresh.count("<loc>")
    print(f"sitemap.xml regenerated: {n} URLs")


if __name__ == "__main__":
    main()
