#!/usr/bin/env python3
"""Regenerate feed.xml from blog/index.html — the single source of post truth.

CLAUDE.md carried a deliberate "no RSS feed" decision, and its reasoning was
sound: a hand-written feed would be one more hand-maintained file with the same
drift profile as sitemap.xml, and a generator would mean the build step this
repo has rejected.

This answers that objection rather than overruling it:

  * The feed is GENERATED from blog/index.html's cards, so it is never authored
    by hand and cannot disagree with the site by neglect.
  * It is generated ON DEMAND by running this script, not by a build step. The
    published tree stays plain static files; GitHub Pages does nothing new.
  * check_site.py INV-31 fails if feed.xml and the blog index disagree, so a new
    post that forgets the feed is caught by the same gate that catches every
    other cross-file miss — which is strictly better than the status quo, where
    sitemap.xml had no gate at all (INV-32 now covers that too).

Usage:
    python3 scripts/gen_feed.py            # rewrite feed.xml
    python3 scripts/gen_feed.py --check    # exit 1 if feed.xml is out of date
"""
import html
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SITE = "https://anirach.com"
CARD = re.compile(r'<a href="([a-z0-9-]+\.html)" class="card">(.*?)</a>', re.S)


def text_of(fragment: str) -> str:
    return html.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", fragment))).strip()


def first_commit_date(rel: str) -> str:
    out = subprocess.run(
        ["git", "log", "--diff-filter=A", "--format=%ad",
         "--date=format:%a, %d %b %Y %H:%M:%S +0700", "--follow", "--", rel],
        cwd=ROOT, capture_output=True, text=True).stdout.strip()
    return out.split("\n")[-1] if out else "Sat, 07 Mar 2026 09:00:00 +0700"


def build() -> str:
    idx = (ROOT / "blog" / "index.html").read_text(encoding="utf-8")
    items = []
    for m in CARD.finditer(idx):
        href, block = m.group(1), m.group(2)
        # Level-agnostic on purpose. The ladder has been re-cut twice (h2 -> h4
        # in 635eb94/4a31036, then h4 -> h3 when the redundant "Technology"
        # category band was deleted on 2026-08-26). A hard-coded level makes
        # this silently return no title and drop every item from the feed.
        t = re.search(r'<(h[1-6]) class="card__title">(.*?)</\1>', block, re.S)
        e = re.search(r'<p class="card__excerpt">(.*?)</p>', block, re.S)
        if not t:
            continue
        # group(1) is the tag NAME (the backreference), group(2) the title
        items.append((href, text_of(t.group(2)),
                      text_of(e.group(1)) if e else "",
                      first_commit_date(f"blog/{href}")))
    esc = lambda x: html.escape(x, quote=False)
    body = "\n".join(
        f"""    <item>
      <title>{esc(t)}</title>
      <link>{SITE}/blog/{h}</link>
      <guid isPermaLink="true">{SITE}/blog/{h}</guid>
      <pubDate>{d}</pubDate>
      <description>{esc(ex)}</description>
    </item>""" for h, t, ex, d in items)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/gen_feed.py from blog/index.html. Do not hand-edit:
     check_site.py INV-31 fails when this file and the blog index disagree. -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Anirach Mingkhwan — Blog</title>
    <link>{SITE}/blog/</link>
    <atom:link href="{SITE}/feed.xml" rel="self" type="application/rss+xml"/>
    <description>Articles on AI agents, DevOps and software engineering by Dr. Anirach Mingkhwan, Associate Professor at KMUTNB.</description>
    <language>th</language>
{body}
  </channel>
</rss>
"""


def main() -> int:
    feed = ROOT / "feed.xml"
    new = build()
    if "--check" in sys.argv:
        cur = feed.read_text(encoding="utf-8") if feed.exists() else ""
        if cur == new:
            print("feed.xml is current")
            return 0
        print("feed.xml is STALE — run: python3 scripts/gen_feed.py")
        return 1
    feed.write_text(new, encoding="utf-8")
    print(f"feed.xml regenerated: {new.count('<item>')} items")
    return 0


if __name__ == "__main__":
    sys.exit(main())
